### ISSUE TITLE
gitignore 업데이트 해두었습니다.

### ISSUE THREAD

**Issue by giftof** [42StudyGame/Unity_01#32]
gitignore 아래처럼 업데이트 해두었습니다.

```
/**/week*/**/[Ll]ibrary/
/**/week*/**/[Tt]emp/
/**/week*/**/[Oo]bj/
/**/week*/**/[Bb]uild/
/**/week*/**/[Bb]uilds/
/**/week*/**/[Ll]ogs/
/**/week*/**/[Mm]emoryCaptures/

```
이제부터는, [week0x] 폴더 아래에 유니티 프로젝트 생성하신 상태로 push해도, 의미있는 파일만 올라갈것입니다.
cs파일만 따로 올리실 필요가 없습니다. 

(아마두요... ^^)

git잘알 분 계시면, 위 내용대로 해도 될지 확인 한번 해주세요 ^^

**Comment by giftof** [comment]
일단 프로젝트를 통으로 올리시면, 좋은점이...

다른분이 그대로 받아서 유니티에디터로 바로 열 수 있게됩니다.
dodge나 uni-run같은걸 만들기 시작하면, 파일만 올리기 번거로우실꺼고,
자신이 만들어놓은 프로젝트를 다른사람이 clone받아 확인하기도 쉬워집니다 :)

**Comment by sangtale** [comment]
앗... .gitignore 설정을 금방 마쳤는데 이 이슈를 진작에 봤더라면...  🥲 감사합니다!!
